export const dummyInvoices = [
  {
    id: "INV0001",
    vendor: "xyz Vendor",
    dateCreated: "4 Apr 2024 - 4:48 PM",
    dueDate: "9 May 2024",
    amountDue: 0,
    totalAmount: 200000,
    status: "Paid Invoice",
    statusColor: "success",
  },
  {
    id: "INV0002",
    vendor: "xyz Vendor",
    dateCreated: "4 Apr 2024 - 4:48 PM",
    dueDate: "9 May 2024",
    amountDue: 100000,
    totalAmount: 200000,
    status: "Partially Paid Invoice",
    statusColor: "warning",
  },
  {
    id: "INV0003",
    vendor: "xyz Vendor",
    dateCreated: "4 Apr 2024 - 4:48 PM",
    dueDate: "9 May 2024",
    amountDue: 200000,
    totalAmount: 200000,
    status: "Unpaid Invoice",
    statusColor: "error",
  },
  {
    id: "INV0004",
    vendor: "xyz Vendor",
    dateCreated: "4 Apr 2024 - 4:48 PM",
    dueDate: "9 May 2024",
    amountDue: 0,
    totalAmount: 200000,
    status: "Paid Invoice",
    statusColor: "success",
  },
  {
    id: "INV0005",
    vendor: "xyz Vendor",
    dateCreated: "4 Apr 2024 - 4:48 PM",
    dueDate: "9 May 2024",
    amountDue: 100000,
    totalAmount: 200000,
    status: "Partially paid Invoice",
    statusColor: "warning",
  },
  {
    id: "INV0006",
    vendor: "xyz Vendor",
    dateCreated: "4 Apr 2024 - 4:48 PM",
    dueDate: "9 May 2024",
    amountDue: 200000,
    totalAmount: 200000,
    status: "Unpaid Invoice",
    statusColor: "error",
  },
];

export const dummyPurchaseOrder = {
  id: "PO00001",
  date: "4 Apr 2024 - 4:48 PM",
  createdBy: "Firstname Lastname",
  invoicingMethod: "Ordered Quantity",
  vendor: {
    name: "Cee Que Enterprise",
    address: "5, Vendor Address",
    email: "vendoremail@gmail.com",
  },
  currency: "Naira (₦)",
  paymentTerms: "Payment terms will be typed here for clarifications",
  purchasePolicy: "Purchase policy will be typed here for clarifications",
  deliveryTerms: "Delivery terms will be typed here for clarifications",
  products: [
    {
      name: "Enter a product name",
      description: "Enter a description",
      qty: 0,
      unitOfMeasure: "Kg",
      estimatedUnitPrice: "000.000",
      totalPrice: "000.000",
    },
  ],
  total: "000.000",
};
